import type { NextPage } from 'next'
import Head from 'next/head'
import {Button} from "antd";
import {RiseOutlined,BarChartOutlined,MoneyCollectOutlined,HighlightOutlined} from "@ant-design/icons";
const Home: NextPage = () => {
    const contentStyle = {

    };
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div id="bannerImg">
                    <div id="banner">
                        <h1 className='h1' style={{color:"white"}}>问卷调查? 用快速投就够了!</h1>
                        <h2 className='h3' style={{color:"white"}}>快速创建,便捷填写</h2>
                        <Button type="primary" danger style={{width:240,height:56,marginTop:50,fontSize:'1.25rem'}}>免费开始</Button>
                    </div>
                </div>
                <section>
                    <div id="advantage">
                        <h2 className='h1'>为什么使用快速投?</h2>
                        <div className="advantageItem">
                            <div className="advantageItemIcon"><RiseOutlined /></div>
                            <div className="advantageItemTitle">快速创建问卷</div>
                            <div className="advantageItemSummary">通过后台页面的组件快速创建自己的调查问卷</div>
                        </div>

                        <div className="advantageItem">
                            <div className="advantageItemIcon"><BarChartOutlined /></div>
                            <div className="advantageItemTitle">直观获取数据</div>
                            <div className="advantageItemSummary">通过可视化组件展示问卷数据,更加直观的获取结果</div>
                        </div>

                        <div className="advantageItem">
                            <div className="advantageItemIcon"><MoneyCollectOutlined /></div>
                            <div className="advantageItemTitle">网站永远免费</div>
                            <div className="advantageItemSummary">网站保证未来不会推出VIP等收费项目,保证用户良好体验</div>
                        </div>

                        <div className="advantageItem">
                            <div className="advantageItemIcon"><HighlightOutlined /></div>
                            <div className="advantageItemTitle">用户填写方便</div>
                            <div className="advantageItemSummary">用户无需登录,直接填写问卷,优化操作速度并节省时间</div>
                        </div>
                    </div>

                </section>
            </main>
            <style jsx>
                {`
                     #banner{height:100vh;min-height: 100vh;min-width: 500px;display: flex;justify-content: center;align-content: center;flex-wrap: wrap;background-color: rgba(57, 49, 49, 0.7);}
                     #bannerImg{background-image: url("/banner.jpg")}
                    .h1{width: 100%;text-align: center;font-size: 3rem;font-weight: bold}
                    .h2{width: 100%;text-align: center;font-size: 1.5rem}
                    .h3{width: 100%;text-align: center;font-size: 1.25rem}
                    #advantage{padding:140px 0;display:flex;justify-content: space-around;align-content: center;flex-wrap: wrap}
                    .advantageItem{width: 25%;text-align: center}
                    .advantageItemIcon{font-size: 5rem}
                    .advantageItemTitle{font-size: 1.5rem}
                    .advantageItemSummary{font-size: 1rem;color: #8c8889;padding: 0 25%}
                `}
            </style>
        </>
    )
}

export default Home
